
development:
  host: localhost
  database: helix_development

test:
  host: localhost
  database: helix_test

# set these environment variables on your prod server
production:
  host: localhost #
  database: helix_prod #
  # slaves:
  #   - host: slave1.local
  #     port: 27018
  #   - host: slave2.local
  #     port: 27019
